### ISSUE TITLE
Missing files on wordpress.org

### ISSUE THREAD

**Issue by brogr** [bahiirwa/Upgrade-for-Unattach-Re-Attach-Media-Attachments#2]
The plugin’s ZIP file hosted on https://wordpress.org/plugins/upgrade-for-unattach-re-attach-media-attachments/ is missing files (in includes/), which lead to a PHP fatal error. Can you please re-upload a ZIP that includes all files? Thanks

**Comment by bahiirwa** [comment]
Oh. Thank you. Let me fix that.

**Comment by bahiirwa** [comment]
I have since fixed this. Test and let me know. 

I request you to close the ticket if all is well. Thank you again.

**Comment by brogr** [comment]
Looks good. Except that I'd change the version to 1.2.1 so that WordPress installations pick up on the upgrade...
